#ifndef TREEANALYZER_FRAMEWORK_PROCESSORS_INTERFACE_CORRECTIONHELPER_H_
#define TREEANALYZER_FRAMEWORK_PROCESSORS_INTERFACE_CORRECTIONHELPER_H_

namespace TAna {
namespace CorrHelp {
enum CORRTYPE {NONE, DOWN, NOMINAL, UP};
}


}



#endif
